package view;

import javax.swing.*;
import dao.UsuarioDAO;
import model.Usuario;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VentanaUsuario {
    public JPanel panel1;
    private JTabbedPane tabbedPane1;
    private JTabbedPane tabbedPane2;
    private JTabbedPane tabbedPane3;
    private JTextField txtNombreUsuario;
    private JTextField txtCorreoUsuario;
    private JLabel lblNombre;
    private JPasswordField txtContrasenaUsuario;
    private JButton btnActualizarUsuario;
    private Usuario usuario;
    private boolean editando = false;

    public VentanaUsuario(Usuario usuario) {

        this.usuario = usuario;

        // Cargar datos usuario
        cargarDatos();

        // Bloquear campos inicialmente
        bloquearCampos();

        // Botón actualizar
        btnActualizarUsuario.addActionListener(
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {

                        actualizarDatos();
                    }
                });
    }

    // Mostrar datos usuario
    private void cargarDatos() {

        lblNombre.setText("Bienvenid@ " + usuario.getNombre());

        txtNombreUsuario.setText(usuario.getNombre());

        txtCorreoUsuario.setText(usuario.getCorreo());

        txtContrasenaUsuario.setText(usuario.getPassword());
    }

    // Bloquear campos
    private void bloquearCampos() {

        txtNombreUsuario.setEditable(false);

        txtCorreoUsuario.setEditable(false);

        txtContrasenaUsuario.setEditable(false);
    }

    // Desbloquear campos
    private void desbloquearCampos() {

        txtNombreUsuario.setEditable(true);

        txtCorreoUsuario.setEditable(true);

        txtContrasenaUsuario.setEditable(true);
    }

    // Actualizar datos usuario
    private void actualizarDatos() {

        // PRIMER CLICK
        if (!editando) {

            int confirmacion =
                    JOptionPane.showConfirmDialog(
                            null,
                            "¿Seguro deseas modificar tus datos?",
                            "Confirmación",
                            JOptionPane.YES_NO_OPTION
                    );

            if (confirmacion == JOptionPane.YES_OPTION) {

                desbloquearCampos();

                editando = true;

                btnActualizarUsuario.setText(
                        "Guardar Cambios"
                );
            }

        }

        // SEGUNDO CLICK
        else {

            usuario.setNombre(
                    txtNombreUsuario.getText()
            );

            usuario.setCorreo(
                    txtCorreoUsuario.getText()
            );

            usuario.setPassword(
                    String.valueOf(
                            txtContrasenaUsuario.getPassword()
                    )
            );

            UsuarioDAO usuarioDAO =
                    new UsuarioDAO();

            usuarioDAO.actualizar(usuario);

            lblNombre.setText(
                    "Bienvenid@ " +
                            usuario.getNombre()
            );

            bloquearCampos();

            editando = false;

            btnActualizarUsuario.setText(
                    "Actualizar Datos"
            );

            JOptionPane.showMessageDialog(
                    null,
                    "Datos actualizados correctamente"
            );
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        panel1.add(tabbedPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Mi Perfil", panel2);
        final JLabel label1 = new JLabel();
        label1.setText("Nombre");
        panel2.add(label1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombreUsuario = new JTextField();
        panel2.add(txtNombreUsuario, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Correo");
        panel2.add(label2, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCorreoUsuario = new JTextField();
        panel2.add(txtCorreoUsuario, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblNombre = new JLabel();
        lblNombre.setText("Label");
        panel2.add(lblNombre, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Contraseaña");
        panel2.add(label3, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Estos son tus datos:");
        panel2.add(label4, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtContrasenaUsuario = new JPasswordField();
        panel2.add(txtContrasenaUsuario, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tabbedPane2 = new JTabbedPane();
        tabbedPane1.addTab("Mis Tickets", tabbedPane2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane2.addTab("Mis tickets", panel3);
        tabbedPane3 = new JTabbedPane();
        tabbedPane1.addTab("Estado del ticket", tabbedPane3);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane3.addTab("Estado del ticket", panel4);
        btnActualizarUsuario = new JButton();
        btnActualizarUsuario.setText("Actualizar Datos");
        panel1.add(btnActualizarUsuario, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
